//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int num_track { get; set; }
        public int duration { get; set; }
        public System.DateTime DateReleased { get; set; }
        public double Price { get; set; }
        public Nullable<int> Artist_ID { get; set; }
        public Nullable<int> Genre_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        public virtual User User { get; set; }
    }
}
